### ISSUE TITLE
OBS Usability Issue

### ISSUE THREAD

**Issue by MrTeeXD** [wolf-plugins/wolf-shaper#120]
So OBS has support for VST Plugins and wolfshaper has a problem where the UI does not move at all when opened in OBS Studio and here is a gif to prove it : 
![oZKviu2wBy](https://user-images.githubusercontent.com/37266538/59638307-51fa0480-9158-11e9-917b-122c01116be5.gif)

**Comment by pdesaulniers** [comment]
Ah, interesting. 

Could you check if Dragonfly Reverb has the same issue? https://github.com/michaelwillis/dragonfly-reverb.git

If so, it's either a bug in DPF, or a bug in OBS.

**Comment by MrTeeXD** [comment]
Yep, same thing

**Comment by pdesaulniers** [comment]
OK, thanks for reporting.

@falkTX, I suppose this is a bug in OBS?

**Comment by falkTX** [comment]
Could be, perhaps OBS is not sending the mouse events properly, or not giving the child window focus.
I recommend trying other plugins, something not made with DPF, and check if they work or not.
There are not many linux VST FX plugins though (that are not made with Juce, since Juce often does very nasty things).
overtonedsp is something to try, their demo versions.

**Comment by falkTX** [comment]
wait, is this bug under windows?

**Comment by pdesaulniers** [comment]
The window decoration in the .gif looks like Windows, so I'd say yes. I don't think OBS supports VSTs on Linux as of now.

Relevant submodule: https://github.com/obsproject/obs-vst

Perhaps it would be good to open an issue there.
