### ISSUE TITLE
Switch to upstream DPF

### ISSUE THREAD

**Issue by pdesaulniers** [wolf-plugins/wolf-shaper#132]
Get rid of this fork: https://github.com/wolf-plugins/DPF
Switch to https://github.com/DISTRHO/DPF instead, to make maintenance easier.

**Comment by reidevries** [comment]
I actually did this on my graphic-dynamics plugin that im working on and it required me to reimplement the right click menu as a widget rather than a window, and store it in the main UI class. Had to do this because I upstream DPF uses a different pugl version which didn't expose the onFocusOut callback, so the right click menu wouldn't close when the user clicked outside the window.

Since I've already done this, I could probably easily reintegrate the changes into wolf-shaper? My version does have some minor UX differences: If the user right clicks a node very close to the graph edge, it will display the graph to the right or above the cursor. And if the user's mouse leaves the graph area, the menu will close. I did that basically to avoid having to deal with draw ordering and widget focus stuff but it kinda makes sense to me that the right click menu would only show up in the graph anyway.

heres my [MenuWidget.hpp](https://github.com/reidevries/GraphicDynamics/blob/menuwidget/plugins/graphic-dynamics/Common/Widgets/MenuWidget.hpp) and [MenuWidget.cpp](https://github.com/reidevries/GraphicDynamics/blob/menuwidget/plugins/graphic-dynamics/Common/Widgets/src/MenuWidget.cpp). I could probably get it integrated into wolf shaper in a day or so since I did it once already.

**Comment by pdesaulniers** [comment]
>  I could probably easily reintegrate the changes into wolf-shaper? 

I think that would be great!

> And if the user's mouse leaves the graph area, the menu will close.

I fear closing the menu when the mouse leaves the graph might be a bit annoying for the user :/ As a workaround, maybe the menu widget could be turned into an overlay? That way, it could intercept all mouse clicks and mouse moves in the UI when needed. I'm thinking of something like this: https://jsfiddle.net/secretgspot/68qRc/

Anyway, off the top of my head, we'd also need to disable mouse cursor manipulation features (setCursorPos, setCursorStyle, etc) or contribute them to upstream (see https://github.com/DISTRHO/DPF/issues/142)

Also, NanoWidget subwidgets work differently in upstream DPF (I vaguely describe this in https://github.com/DISTRHO/DPF/issues/68)

**Comment by pdesaulniers** [comment]
@reidevries FYI, I am starting the migration to upstream DPF. I will leave the context menu unimplemented for now.

**Comment by reidevries** [comment]
> @reidevries FYI, I am starting the migration to upstream DPF. I will leave the context menu unimplemented for now.

Cool - I've heard falktx mention that they are updating pugl soon, although no specific date. Possibly that will allow us to get window focus from pugl again. But either way I'll fork the upstream dpf branch sometime hopefully in the next few days

**Comment by pdesaulniers** [comment]
> I've heard falktx mention that they are updating pugl soon, although no specific date.

Yes, I'm following this branch closely! :)

I just ported https://github.com/wolf-plugins/wolf-shaper/pull/142 to the pugl-upstream-v2 branch. Most widgets are not rendering correctly right now, but it's a start:

![image](https://user-images.githubusercontent.com/23723605/118410341-eb8c0280-b65c-11eb-81af-72b76174ca1f.png)

**Comment by pdesaulniers** [comment]
OK, it looks nicer now:

![image](https://user-images.githubusercontent.com/23723605/119225923-96287900-bad4-11eb-9de5-52004a650889.png)

I see that the vertices are being clipped, and the stroke paint on the knobs does not look correct.

**Comment by pdesaulniers** [comment]
OK, Wolf Shaper now runs on upstream DPF! Let's close this issue in favor of https://github.com/wolf-plugins/wolf-shaper/issues/143.
